
@server = http://192.168.0.2:3000


POST {{server}}/offerup/settings
Content-Type: application/json

{
    "query": "ps4",
    "delievery": "p",
    "price_min": "150",
    "price_max": "210",
    "radius": "5",
    "yearMin": "2020",
    "zipCode": "60645"
}


###
GET {{server}}/offerup/settings
Content-Type: application/json

###
POST {{server}}/offerup/extract


###
GET {{server}}/offerup/blacklist

###
POST {{server}}/offerup/blacklist/1

###
DELETE {{server}}/offerup/blacklist/1


###
GET {{server}}/offerup/data


### 
POST {{server}}/offerup/start-job


### 
POST {{server}}/offerup/end-job

### 
GET {{server}}/offerup/job-status

### 
POST {{server}}/offerup/expo-token
Content-Type: application/json

{
    "token": "hahaha"
}